version: "3"

services:
  web_dev:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: ["flask", "run", "--reload"]
